andrewkroh/gvm

- CHANGELOG.md
- golang/golang.go
Changed code to extract the Go distribution directly into HOME instead of extracting to a temp dir and then moving to HOME. On some systems using `os.Rename` (move) across devices resulted in EXDEV (invalid cross-device link).
Fixes #1
> Avoid using file rename

- CHANGELOG.md
- README.md
- gvm_test.go
Added a test case to check that the GOROOT/bin/go exists and is the correct Go version.
Also updated the docs to use Go 1.9 in the examples.
> Add tests to check paths

- README.md
The current windows batch command in README.md is wrong and results in the following error:
```
C:\FOR /f "tokens=*" %i IN ('"gvm.exe" gvm 1.9') DO %i
gvm: error: unexpected 1.9
```
Removed the extra gvm in the commit.
> Corrected Windows Batch command

- README.md
By default poweshell at least on windows 2012 default to TLS1.0, github
requires TLS1.2 so we have to change the value before downloading the
executable.
> Add command to set the Powershell TLS version before downloading

- cmd.go
- cmd/gvm/avail.go
- cmd/gvm/gvm.go
- cmd/gvm/init.go
- cmd/gvm/install.go
- cmd/gvm/use.go
- gvm.go
- srcrepo.go
- util.go
- version.go
- Building go is optional. If binaries are installed only, no source code is ever checked out or downloaded
- Source code is checked out as bare repository into ~/.gvm/cache/go
- To force building from source pass `-b` flag to `use` or `install` command (version is only build if not already installed)
- Installer tries to get binary version first. Only if this fails we fall back to building from source (local source checkout can act as cache)
- Version `tip` is always build from source
- When using `tip`, the cache is only updated once per day. `tip` is rebuild if new commits are found in the repository
- Introduce `gvm init` command. `init` clones the git repository or forces a `git fetch`.
- Expose some more flags like target os, arch, gvm home directory, ...
Building from source …
> Add support to install go from source

- srcrepo.go
Do not use a bare repository and use 'git pull', to guarantee the cached
source repository can be updated correctly.
> Fix cached git repo not being updates

- CHANGELOG.md
- cmd/gvm/gvm.go
- common/common.go
and set timeout on http get.
In an attempt to combat CI issues like:
```
gvm: error: http get failed: Get https://storage.googleapis.com/golang/go1.11.4.linux-amd64.tar.gz: dial tcp 173.194.197.128:443: i/o timeout
```
> retry file downloads 3 times

- README.md
%i is for use on command lines only.
For batch scripts %i should be substituted with %%i.
> Add cmd.exe example details

- CHANGELOG.md
- README.md
- cmd/gvm/internal/shellfmt/format.go
Fix output of `--format match` to remove a stray `$` character
> Fix output of --format match for Windows

- CHANGELOG.md
- binrepo.go
- gvm.go
The code silently falls back to installing from source when a binary
package fails to install. So log a warning when this happens.
> Log warning when binary package install fails

- CHANGELOG.md
- common/common.go
- common/extract.go
- go.mod
- go.sum
- srcrepo.go
- util.go
common.Rename tries to use os.Rename but falls-back to copy/delete on
failure. This allows operation across disks to succeed.
Also add better error handling in the extract functions.
> Replace os.Rename with common.Rename

- CHANGELOG.md
- common/common.go
- go.sum
- gvm.go
When the install from a binary package fails it falls back to installing from source. Tthe only case where the fallback
should occur is when the server responds with a 404 that no binary package exists. Otherwise it's falling back on
various IO or permissions errors.
Fixes #30
> Fall back to source install only when binary URL is 404

- cmd/gvm/use.go
Mostly to enable `gvm use tip -n`.
```
[15:02:09] ~/src/gvm (use-no-install) $ cat ~/.gvm/cache/go.meta 
{"Updated":"2021-01-07T14:23:47.883139-05:00"}
[15:02:15] ~/src/gvm (use-no-install) $ gvm use tip -n
export GOROOT="/Users/gil/.gvm/versions/gotip.darwin.amd64"
export PATH="/Users/gil/.gvm/versions/gotip.darwin.amd64/bin:$PATH"
[15:02:18] ~/src/gvm (use-no-install) $ cat ~/.gvm/cache/go.meta 
{"Updated":"2021-01-07T14:23:47.883139-05:00"}
[15:02:19] ~/src/gvm (use-no-install) $ gvm use tip
export GOROOT="/Users/gil/.gvm/versions/gotip.darwin.amd64"
export PATH="/Users/gil/.gvm/versions/gotip.darwin.amd64/bin:$PATH"
[15:03:11] ~/src/gvm (use-no-install) $ cat ~/.gvm/cache/go.meta 
{"Updated":"2021-01-08T15:02:23.408087-05:00"}
```
> add gvm use -n/--no-install option

- CHANGELOG.md
- cmd/gvm/avail.go
- gvm.go
- srcrepo.go
- version.go
This improves the `gvm available` command to ensure the data returned is as accurate as possible.
It addresses a few different issues.
The command uses the a cached copy of the Go git repo to list the available version tags. This will
now refresh the source repo if the cache is not from the current day.
The tags from the source repo were the only ones that were listed in the output. Each of those versions
were then annotated with whether a binary version is available. So if the source repo was stale you
would never newly released binary versions. This changes the output to merge the list of source repo
tags and binary releases so that you generally always see the latest data.
Fixes #39
[available-no-source.txt](https://github.com/andrewkroh/gvm/files/7475010/available-no-source.txt)
``` …
```
> Improve 'gvm available'

- CHANGELOG.md
- binrepo.go
- cmd/gvm/gvm.go
- common/common.go
- gvm.go
Add new flag to control http timeouts.
```
Optional flags:
--http-timeout=3m        Timeout for HTTP requests.
```
Closes #43
> Add --http-timeout flag

- CHANGELOG.md
- cmd/gvm/gvm.go
The code is setting the GOOS value when it should have been setting GOARCH.
> Fix GVM_ARCH env var and --arch CLI flag

- .github/workflows/golangci-lint.yml
- .github/workflows/goreleaser.yml
- cmd/gvm/gvm.go
- cmd/gvm/use.go
- cmd/gvm/use_test.go
- srcrepo.go
- version.go
Add an explicit test that installs Go from source.
Skip certain tests based on the runtime GOOS and GOARCH because you cannot install some of the specified versions that are older on platforms that newly gained Go support.
> Test installing from source

- cmd/gvm/use_test.go
- common/extract.go
- version.go
This makes the assumption that starting in 1.21 all future release will always include a patch number in their naming.
For example, previous versions were named like '1.20' and then '1.20.1' (there was no '1.20.0'). Now with 1.21 the first release was versioned as '1.20.0'.
> adjust version naming convention for >=1.21

- CHANGELOG.md
- binrepo.go
- common/common.go
Currently `gvm` makes three attempts at retrying a failed download, but it doesn't wait in between.
This commit adds rudimentary wait time between download attempts. It also increases the number
of retries to 5.
In a future refactoring we could use `go-retryablehttp`[^1] (we'd still need to guard for errors with `io.Copy`) but keeping the
improvement short for now, hoping to reduce download related CI failures.
[^1]: https://pkg.go.dev/github.com/hashicorp/go-retryablehttp#section-readme
> Add wait between retries when there are download errors

- .github/dependabot.yml
- .github/workflows/go.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/goreleaser.yml
Use a matrix for testing.
Add concurrency settings.
Enable dependabot.
goreleaser - Use --clean instead of --rm-dist
> ci - refactor GH actions

- README.md
<Actions>
<p>1 file(s) updated with &#34; 1.22.2&#34;:&#xA;&#x9;* README.md&#xA;</p>
<details>
<summary>1.22.2</summary>
<pre>no GitHub Release found for go1.22.2 on &#34;https://github.com/golang/go&#34;</pre>
</details>
</details>
<a href="https://github.com/andrewkroh/updatecli-configs/actions/runs/8558812287">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
> [Automation] Bump Go version to 1.22.2

- README.md
<Actions>
<p>1 file(s) updated with &#34; 1.22.3&#34;:&#xA;&#x9;* README.md&#xA;</p>
<details>
<summary>1.22.3</summary>
<pre>no GitHub Release found for go1.22.3 on &#34;https://github.com/golang/go&#34;</pre>
</details>
</details>
<a href="https://github.com/andrewkroh/updatecli-configs/actions/runs/8989662642">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
> [Automation] Bump Go version to 1.22.3

- CHANGELOG.md
- cmd/gvm/internal/shellfmt/format.go
Fix for #81
Newish to Go, suggestions/changes welcome.
> Path separator as colon on pwsh Linux

- README.md
<Actions>
<p>1 file(s) updated with &#34; 1.22.4&#34;:&#xA;&#x9;* README.md&#xA;</p>
<details>
<summary>1.22.4</summary>
<pre>no GitHub Release found for go1.22.4 on &#34;https://github.com/golang/go&#34;</pre>
</details>
</details>
<a href="https://github.com/andrewkroh/updatecli-configs/actions/runs/9377383304">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
> [Automation] Bump Go version to 1.22.4

- README.md
<Actions>
<p>1 file(s) updated with &#34; 1.22.5&#34;:&#xA;&#x9;* README.md&#xA;</p>
<details>
<summary>1.22.5</summary>
<pre>no GitHub Release found for go1.22.5 on &#34;https://github.com/golang/go&#34;</pre>
</details>
</details>
<a href="https://github.com/andrewkroh/updatecli-configs/actions/runs/9827544452">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
> [Automation] Bump Go version to 1.22.5

- README.md
<Actions>
<p>1 file(s) updated with &#34; 1.22.6&#34;:&#xA;&#x9;* README.md&#xA;</p>
<details>
<summary>1.22.6</summary>
<pre>no GitHub Release found for go1.22.6 on &#34;https://github.com/golang/go&#34;</pre>
</details>
</details>
<a href="https://github.com/andrewkroh/updatecli-configs/actions/runs/10277748518">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
> [Automation] Bump Go version to 1.22.6

- README.md
<Actions>
<p>1 file(s) updated with &#34; 1.23.1&#34;:&#xA;&#x9;* README.md&#xA;</p>
<details>
<summary>1.23.1</summary>
<pre>no GitHub Release found for go1.23.1 on &#34;https://github.com/golang/go&#34;</pre>
</details>
</details>
<a href="https://github.com/andrewkroh/updatecli-configs/actions/runs/10760201725">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
> [Automation] Bump Go version to 1.23.1

- README.md
<Actions>
<p>1 file(s) updated with &#34; 1.23.2&#34;:&#xA;&#x9;* README.md&#xA;</p>
<details>
<summary>1.23.2</summary>
<pre>no GitHub Release found for go1.23.2 on &#34;https://github.com/golang/go&#34;</pre>
</details>
</details>
<a href="https://github.com/andrewkroh/updatecli-configs/actions/runs/11142801310">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
> [Automation] Bump Go version to 1.23.2

- README.md
<Actions>
<p>1 file(s) updated with &#34; 1.23.3&#34;:&#xA;&#x9;* README.md&#xA;</p>
<details>
<summary>1.23.3</summary>
<pre>no GitHub Release found for go1.23.3 on &#34;https://github.com/golang/go&#34;</pre>
</details>
</details>
<a href="https://github.com/andrewkroh/updatecli-configs/actions/runs/11765446215">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
> [Automation] Bump Go version to 1.23.3

- README.md
<Actions>
<p>1 file(s) updated with &#34; 1.23.4&#34;:&#xA;&#x9;* README.md&#xA;</p>
<details>
<summary>1.23.4</summary>
<pre>no GitHub Release found for go1.23.4 on &#34;https://github.com/golang/go&#34;</pre>
</details>
</details>
<a href="https://github.com/andrewkroh/updatecli-configs/actions/runs/12206262346">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
> [Automation] Bump Go version to 1.23.4

- README.md
<Actions>
<p>1 file(s) updated with &#34; 1.23.5&#34;:&#xA;&#x9;* README.md&#xA;</p>
<details>
<summary>1.23.5</summary>
<pre>no GitHub Release found for go1.23.5 on &#34;https://github.com/golang/go&#34;</pre>
</details>
</details>
<a href="https://github.com/andrewkroh/updatecli-configs/actions/runs/12853859337">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
> [Automation] Bump Go version to 1.23.5

- README.md
<Actions>
<p>1 file(s) updated with &#34; 1.23.6&#34;:&#xA;&#x9;* README.md&#xA;</p>
<details>
<summary>1.23.6</summary>
<pre>no GitHub Release found for go1.23.6 on &#34;https://github.com/golang/go&#34;</pre>
</details>
</details>
<a href="https://github.com/andrewkroh/updatecli-configs/actions/runs/13159074565">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
> [Automation] Bump Go version to 1.23.6

- README.md
<Actions>
<p>1 file(s) updated with &#34; 1.24.1&#34;:&#xA;&#x9;* README.md&#xA;</p>
<details>
<summary>1.24.1</summary>
<pre>no GitHub Release found for go1.24.1 on &#34;https://github.com/golang/go&#34;</pre>
</details>
</details>
<a href="https://github.com/andrewkroh/updatecli-configs/actions/runs/13748735565">GitHub Action workflow link</a>
</action>
</Actions>
---
<table>
<tr>
</td>
<td>
<p>
</p>
<br /> …
> [Automation] Bump Go version to 1.24.1
